
IF DB_Id('BookLibrary') IS NULL
CREATE DATABASE BookLibrary
GO

USE BookLibrary
IF(NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Categories'))
CREATE TABLE Categories(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Name VARCHAR(20) NOT NULL,
DateOfCreating DATE NOT NULL)

IF (NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Books'))
CREATE TABLE Books(
Id INT IDENTITY NOT NULL PRIMARY KEY,
Title VARCHAR(20) NOT NULL,
Isbn VARCHAR(20) NOT NULL,
Author VARCHAR(20) NOT NULL)

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'BooksCategories'))
CREATE TABLE BooksCategories(
BookId INT NOT NULL CONSTRAINT FK_BooksCategories_Books_BookId FOREIGN KEY REFERENCES Books(Id),
CategoryId INT NOT NULL CONSTRAINT FK_BooksCategories_Categories_CategoryId FOREIGN KEY REFERENCES Categories(Id),
PRIMARY KEY (BookId, CategoryId))